sonar.projectKey=cbalderama_PersonalProject
sonar.organization=cbalderama

sonar.sources=apps/mobile/services
sonar.tests=apps/mobile/services/__tests__
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*.test.ts,**/*.test.tsx,**/node_modules/**,**/firebaseConfig.ts